import type { TouristPoint } from "@/types/point";
import { fetchTotalXp, fetchTrails } from "@/services/trailsService";
import { TRAILS_ENABLED } from "@/lib/featureFlags";
import type { LiveFunctionCall } from "@/lib/voice/geminiLiveClient";

export interface VoiceActionContext {
  userId: string;
  userName?: string;
  userEmail?: string;
  points: TouristPoint[];
  searchedPoints?: TouristPoint[];
  userLocation: [number, number] | null;
  preferences?: Record<string, unknown>;
  goToPoint: (point: TouristPoint) => void;
  goToTrailsForCity: (city: string) => void;
  goToTrails: () => void;
  goToMap: () => void;
  goToProfile: () => void;
  openScanner: () => void;
  setHighContrast: (v: boolean) => void;
  setVLibras: (v: boolean) => void;
  setVoiceReading: (v: boolean) => void;
  setReduceMotion: (v: boolean) => void;
  increaseFontScale: () => void;
  decreaseFontScale: () => void;
}

/**
 * Result of executing one function call. `response` is the JSON payload
 * sent back to Gemini as the function's result — Gemini itself phrases
 * the spoken reply from this data, so it must contain ONLY real app data,
 * never prose meant to be read verbatim.
 *
 * Navigation is DEFERRED (`sideEffect` + `navigatesAway`) exactly like the
 * previous architecture: the caller must let the model's audio response
 * finish playing before running sideEffect, otherwise switching screens
 * unmounts VoiceView mid-utterance and cuts the model off.
 */
export interface ExecutedVoiceAction {
  response: Record<string, unknown>;
  sideEffect?: () => void;
  navigatesAway: boolean;
  /** true = user signaled the conversation is over (goodbye/thanks-bye/
   * "pode encerrar" etc). Caller lets the model speak its goodbye line in
   * full, then tears the session down — mirrors how navigatesAway defers
   * to end-of-turn instead of cutting the model off mid-sentence. */
  endsConversation?: boolean;
}

function ok(response: Record<string, unknown>, extra?: Partial<ExecutedVoiceAction>): ExecutedVoiceAction {
  return { response, navigatesAway: false, ...extra };
}

/** Haversine distance in km — good enough for "nearest point" ranking. */
function distanceKm(a: [number, number], b: [number, number]): number {
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const [lat1, lon1] = a;
  const [lat2, lon2] = b;
  const R = 6371;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const sinDLat = Math.sin(dLat / 2);
  const sinDLon = Math.sin(dLon / 2);
  const h = sinDLat * sinDLat + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * sinDLon * sinDLon;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** One-shot fresh geolocation request, used when ctx.userLocation is still
 * null at the moment of a "nearest point" command. */
function requestFreshLocation(): Promise<[number, number] | null> {
  return new Promise((resolve) => {
    if (typeof navigator === "undefined" || !("geolocation" in navigator)) {
      resolve(null);
      return;
    }
    navigator.geolocation.getCurrentPosition(
      (pos) => resolve([pos.coords.latitude, pos.coords.longitude]),
      () => resolve(null),
      { enableHighAccuracy: true, timeout: 6000 }
    );
  });
}

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function pointMatchesCity(point: TouristPoint, city: string): boolean {
  return normalize(point.city).includes(normalize(city)) || normalize(city).includes(normalize(point.city));
}

function pointSummary(p: TouristPoint): Record<string, unknown> {
  return {
    name: p.name,
    category: p.category,
    city: p.city,
    address: p.address || "Endereço não cadastrado",
    description: p.description || null,
    history: p.history || null,
    accessibility: {
      wheelchair: p.accessibility.wheelchair,
      audio: p.accessibility.audio,
      braille: p.accessibility.braille,
      libras: p.accessibility.libras,
      attendance: p.accessibility.attendance,
      // Flatten to plain strings for the voice model — it doesn't need the
      // per-item confirmation state, just readable descriptions.
      details: (p.accessibility.details || []).map((d) => d.texto),
    },
  };
}

/**
 * Executes one function call requested by the model, using ONLY real app
 * data — never text generated by the AI. The returned `response` becomes
 * the function's result; Gemini phrases the actual spoken reply from it
 * on its own.
 */
export async function executeVoiceAction(call: LiveFunctionCall, ctx: VoiceActionContext): Promise<ExecutedVoiceAction> {
  const { name, args } = call;

  switch (name) {
    case "navigate_to_nearest_point": {
      if (ctx.points.length === 0) return ok({ error: "Nenhum ponto turístico cadastrado ainda." });

      let location = ctx.userLocation;
      if (!location) location = await requestFreshLocation();
      if (!location) return ok({ error: "Localização indisponível. Permissão de localização pode estar desativada." });

      let nearest = ctx.points[0];
      let nearestDist = distanceKm(location, [nearest.coords.lat, nearest.coords.lng]);
      for (const p of ctx.points.slice(1)) {
        const d = distanceKm(location, [p.coords.lat, p.coords.lng]);
        if (d < nearestDist) {
          nearest = p;
          nearestDist = d;
        }
      }
      return {
        response: { point: pointSummary(nearest), distanceKm: Number(nearestDist.toFixed(1)) },
        sideEffect: () => ctx.goToPoint(nearest),
        navigatesAway: true,
      };
    }

    case "open_trail_by_city": {
      // Trails feature is off — answer in-conversation, never navigate.
      if (!TRAILS_ENABLED) return ok({ error: "As trilhas não estão disponíveis no momento." });
      const city = String(args.city ?? "").trim();
      if (!city) return ok({ error: "Nome da cidade não informado." });
      const hasAny = ctx.points.some((p) => pointMatchesCity(p, city));
      if (!hasAny) return ok({ error: `Nenhum ponto turístico cadastrado em ${city}.` });
      return {
        response: { city, opened: true },
        sideEffect: () => ctx.goToTrailsForCity(city),
        navigatesAway: true,
      };
    }

    case "list_points_in_city": {
      const city = String(args.city ?? "").trim();
      if (!city) return ok({ error: "Nome da cidade não informado." });
      const matches = ctx.points.filter((p) => pointMatchesCity(p, city));
      if (matches.length === 0) return ok({ error: `Nenhum ponto turístico cadastrado em ${city}.` });
      return ok({ city, count: matches.length, points: matches.slice(0, 8).map(pointSummary) });
    }

    case "find_points": {
      const query = args.query ? normalize(String(args.query)) : "";
      const city = args.city ? String(args.city) : "";
      const category = args.category ? normalize(String(args.category)) : "";
      const wheelchair = args.wheelchair === true;
      const audio = args.audio === true;
      const braille = args.braille === true;
      const libras = args.libras === true;
      const attendance = args.attendance === true;

      let matches = ctx.points;
      if (query) matches = matches.filter((p) => normalize(p.name).includes(query) || normalize(p.category).includes(query));
      if (city) matches = matches.filter((p) => pointMatchesCity(p, city));
      if (category) matches = matches.filter((p) => normalize(p.category).includes(category));
      if (wheelchair) matches = matches.filter((p) => p.accessibility.wheelchair);
      if (audio) matches = matches.filter((p) => p.accessibility.audio);
      if (braille) matches = matches.filter((p) => p.accessibility.braille);
      if (libras) matches = matches.filter((p) => p.accessibility.libras);
      if (attendance) matches = matches.filter((p) => p.accessibility.attendance);

      if (matches.length === 0) return ok({ error: "Nenhum ponto turístico encontrado com esses critérios." });
      if (matches.length === 1) {
        const only = matches[0];
        return {
          response: { count: 1, points: [pointSummary(only)] },
          sideEffect: () => ctx.goToPoint(only),
          navigatesAway: true,
        };
      }
      const first = matches[0];
      return {
        response: { count: matches.length, points: matches.slice(0, 5).map(pointSummary), opening: first.name },
        sideEffect: () => ctx.goToPoint(first),
        navigatesAway: true,
      };
    }

    case "get_point_info": {
      const query = normalize(String(args.query ?? ""));
      if (!query) return ok({ error: "Nome do ponto não informado." });
      const match = ctx.points.find((p) => normalize(p.name).includes(query));
      if (!match) return ok({ error: `Nenhum ponto encontrado com o nome "${args.query}".` });
      return {
        response: { point: pointSummary(match) },
        sideEffect: () => ctx.goToPoint(match),
        navigatesAway: true,
      };
    }

    case "get_point_history": {
      const query = normalize(String(args.query ?? ""));
      if (!query) return ok({ error: "Nome do ponto não informado." });
      const match = ctx.points.find((p) => normalize(p.name).includes(query));
      if (!match) return ok({ error: `Nenhum ponto encontrado com o nome "${args.query}".` });
      return ok({
        name: match.name,
        city: match.city,
        address: match.address || "Endereço não informado",
        history: match.history || match.description || "História e informações detalhadas não cadastradas ainda.",
        description: match.description || null,
        accessibility: match.accessibility,
      });
    }

    case "get_user_info": {
      const xp = await fetchTotalXp(ctx.userId).catch(() => 0);
      return ok({
        userName: ctx.userName || "Visitante",
        email: ctx.userEmail || null,
        totalXp: xp,
        preferences: ctx.preferences || {},
      });
    }

    case "get_search_history": {
      const history = (ctx.searchedPoints || []).slice(0, 5).map(pointSummary);
      return ok({ count: history.length, searches: history });
    }

    case "get_unlocked_badges": {
      // Badges only exist as part of the trails feature.
      if (!TRAILS_ENABLED) return ok({ count: 0, badges: [], error: "As trilhas não estão disponíveis no momento." });
      try {
        const trails = await fetchTrails(ctx.userId);
        const unlocked = trails.filter((t) => t.hasBadge).map((t) => ({
          cityName: t.cityName,
          trailTitle: t.trailTitle,
          badgeTitle: t.badgeTitle,
        }));
        return ok({ count: unlocked.length, badges: unlocked });
      } catch {
        return ok({ count: 0, badges: [] });
      }
    }

    case "play_audio_guide": {
      const query = normalize(String(args.query ?? ""));
      if (!query) return ok({ error: "Nome do ponto não informado." });
      const match = ctx.points.find((p) => normalize(p.name).includes(query));
      if (!match) return ok({ error: `Nenhum ponto encontrado com o nome "${args.query}".` });
      return {
        response: {
          name: match.name,
          hasAudio: Boolean(match.audioUrl || match.audioDescriptionUrl || match.accessibility.audio),
          audioUrl: match.audioUrl || match.audioDescriptionUrl || null,
        },
        sideEffect: () => ctx.goToPoint(match),
        navigatesAway: true,
      };
    }

    case "open_libras_video": {
      const query = normalize(String(args.query ?? ""));
      if (!query) return ok({ error: "Nome do ponto não informado." });
      const match = ctx.points.find((p) => normalize(p.name).includes(query));
      if (!match) return ok({ error: `Nenhum ponto encontrado com o nome "${args.query}".` });
      return {
        response: {
          name: match.name,
          hasLibras: Boolean(match.librasVideoUrl || match.accessibility.libras),
          librasVideoUrl: match.librasVideoUrl || null,
        },
        sideEffect: () => ctx.goToPoint(match),
        navigatesAway: true,
      };
    }

    case "get_top_city": {
      if (ctx.points.length === 0) return ok({ error: "Nenhum ponto turístico cadastrado ainda." });
      const counts = new Map<string, number>();
      for (const p of ctx.points) {
        const city = p.city.trim() || "sem cidade definida";
        counts.set(city, (counts.get(city) ?? 0) + 1);
      }
      let topCity = "";
      let topCount = 0;
      for (const [city, count] of counts) {
        if (count > topCount) {
          topCity = city;
          topCount = count;
        }
      }
      return ok({ city: topCity, pointCount: topCount });
    }

    case "get_total_xp": {
      try {
        const xp = await fetchTotalXp(ctx.userId);
        return ok({ totalXp: xp });
      } catch {
        return ok({ error: "Não foi possível verificar a pontuação agora." });
      }
    }

    case "toggle_accessibility_feature": {
      const feature = String(args.feature ?? "");
      const enabled = typeof args.enabled === "boolean" ? args.enabled : true;

      const applyNow = (effect: () => void): ExecutedVoiceAction => {
        effect();
        return ok({ feature, enabled, applied: true });
      };

      switch (feature) {
        case "vlibras":
          return applyNow(() => ctx.setVLibras(enabled));
        case "high_contrast":
          return applyNow(() => ctx.setHighContrast(enabled));
        case "voice_reading":
          return applyNow(() => ctx.setVoiceReading(enabled));
        case "reduce_motion":
          return applyNow(() => ctx.setReduceMotion(enabled));
        case "font_size_increase":
          return applyNow(() => ctx.increaseFontScale());
        case "font_size_decrease":
          return applyNow(() => ctx.decreaseFontScale());
        default:
          return ok({ error: "Recurso de acessibilidade não reconhecido." });
      }
    }

    case "open_profile":
      return { response: { opened: "profile" }, sideEffect: () => ctx.goToProfile(), navigatesAway: true };

    case "open_qr_scanner":
      return { response: { opened: "qr_scanner" }, sideEffect: () => ctx.openScanner(), navigatesAway: true };

    case "open_map":
      return { response: { opened: "map" }, sideEffect: () => ctx.goToMap(), navigatesAway: true };

    case "open_trails":
      if (!TRAILS_ENABLED) return ok({ error: "As trilhas não estão disponíveis no momento." });
      return { response: { opened: "trails" }, sideEffect: () => ctx.goToTrails(), navigatesAway: true };

    case "end_conversation":
      return { response: { ended: true }, navigatesAway: false, endsConversation: true };

    default:
      return ok({ error: `Função desconhecida: ${name}` });
  }
}
